import type { Company, CompanyDetail } from "../types";
import { esc, safeUrl } from "../ui";
export let companyUnit = localStorage.getItem('company-unit') || 'million';
export let companyMode = localStorage.getItem('company-mode') || 'card';
export const setCompanyDisplay=(key:string,value:string)=>{if(key==='unit')companyUnit=value;else companyMode=value;localStorage.setItem('company-'+key,value);};
export const amount=(value?:number)=>value==null?"—":`${(companyUnit==='eok'?value/100:value).toLocaleString('ko-KR',{maximumFractionDigits:2})}${companyUnit==='eok'?'억원':'백만원'}`;
export const unitControls=()=>`<div class="company-controls" role="group" aria-label="재무 단위">${['million','eok'].map(u=>`<button data-company-unit="${u}" aria-pressed="${companyUnit===u}">${u==='eok'?'억원':'백만원'}</button>`).join('')}</div>`;
export const companyControls=()=>`<div class="company-toolbar"><div class="company-controls"><button data-company-groups>즐겨찾기 설정</button><button data-company-classified>분류 전체보기</button>${['card','list'].map(m=>`<button data-company-mode="${m}" aria-pressed="${companyMode===m}">${m==='card'?'카드':'리스트'}</button>`).join('')}</div>${unitControls()}</div>`;
const colors:Record<string,string>={RED:'빨강',YELLOW:'노랑',GREEN:'초록',BLUE:'파랑',PURPLE:'보라'};
export const companyMark=(c:Company)=>c.isOurCompany?'<span class="badge">우리회사</span>':c.favoriteColor?`<span class="company-color color-${esc(c.favoriteColor)}" title="${esc(colors[c.favoriteColor])} 즐겨찾기">●</span>`:'';
export const companyList=(data:Company[])=>`<div class="company-list-wrap"><table class="company-list"><thead><tr>${['회사명','주소','매출액','영업이익','순이익','분류','메모'].map(v=>`<th>${v}</th>`).join('')}</tr></thead><tbody>${data.map(c=>`<tr data-company="${esc(c.companyId)}" tabindex="0"><td>${companyMark(c)} ${esc(c.companyName)}</td><td>${esc(c.roadAddress??c.address??'—')}</td><td>${amount(c.revenueKrwMillion)}</td><td>${amount(c.operatingIncomeKrwMillion)}</td><td>${amount(c.netIncomeKrwMillion)}</td><td>${esc(c.classification??'—')}</td><td>${esc(c.memo??'—')}</td></tr>`).join('')}</tbody></table></div>`;
export const metadataPanel=(c:Company,groups:{color:string;name:string}[]=[])=>`<article class="detail-section company-metadata" data-metadata-id="${esc(c.companyId)}"><h2>우리회사 · 즐겨찾기 분류</h2><div class="company-controls"><button data-company-our="${c.isOurCompany?'0':'1'}" aria-pressed="${!!c.isOurCompany}">${c.isOurCompany?'우리회사 지정 해제':'우리회사로 지정'}</button></div><label>즐겨찾기<select id="company-color" ${c.isOurCompany?'disabled':''}><option value="">지정 안 함</option>${Object.entries(colors).map(([color,label])=>`<option value="${color}" ${c.favoriteColor===color?'selected':''}>${label} · ${esc(groups.find(g=>g.color===color)?.name||'이름 미설정')}</option>`).join('')}</select></label><label>분류<input id="company-classification" maxlength="10" value="${esc(c.classification)}"></label><label>메모<input id="company-memo" maxlength="40" value="${esc(c.memo)}"></label><button class="secondary" data-company-save>저장</button><span role="status" id="company-save-status"></span></article>`;

export const companyCard=(row:Company,_favorites:Set<string>)=>`<article class="company-card" data-company="${esc(row.companyId)}" tabindex="0"><div class="company-title"><div><b>${esc(row.companyName)}</b><small>${esc(row.businessNumber??row.sminfoKcd)}</small></div><div class="card-actions"><span>${esc(row.companyStatus??"상태 미표시")}</span>${companyMark(row)}</div></div><div class="company-meta-text">${esc(row.classification)} ${esc(row.memo)}</div><div class="company-grid"><dl><dt>대표자</dt><dd>${esc(row.representativeName??"—")}</dd><dt>기업형태</dt><dd>${esc(row.companyType??"—")}</dd><dt>설립일</dt><dd>${esc(row.establishedDate??"—")}</dd></dl><dl><dt>업종</dt><dd>${esc(row.industryName??"—")} ${row.ksicCode?`<small>${esc(row.ksicCode)}</small>`:""}</dd><dt>주요제품</dt><dd>${esc(row.mainProducts??"—")}</dd><dt>주소</dt><dd>${esc(row.roadAddress??row.address??"—")}</dd></dl><dl class="financial"><dt>최근 결산</dt><dd>${esc(row.fiscalYear??"—")}</dd><dt>매출액</dt><dd>${amount(row.revenueKrwMillion)}</dd><dt>영업이익</dt><dd>${amount(row.operatingIncomeKrwMillion)}</dd><dt>당기순이익</dt><dd>${amount(row.netIncomeKrwMillion)}</dd></dl></div></article>`;

const rows=(data:Record<string,unknown>[],columns:[string,string][])=>data.length?`<div class="detail-table"><div class="detail-row head">${columns.map(([,label])=>`<b>${label}</b>`).join("")}</div>${data.map((row)=>`<div class="detail-row">${columns.map(([key])=>`<span>${["revenue","operatingIncome","netIncome","totalAssets"].includes(key)?amount(row[key] as number|undefined):esc(row[key]??"—")}</span>`).join("")}</div>`).join("")}</div>`:'<div class="detail-empty">등록된 정보가 없습니다.</div>';
export const companyDetailView=(d:CompanyDetail,_favorites:Set<string>)=>{const c=d.company; return `<section class="page detail"><button class="back" data-back>← 기업 검색으로 돌아가기</button><header class="page-head"><div><p class="eyebrow">COMPANY DETAIL</p><h1>${esc(c.companyName)}</h1><p>${esc(c.businessNumber??c.sminfoKcd)} · 데이터 기준 ${esc(c.lastCollectedAt??"—")}</p></div>${companyMark(c)}</header><article class="detail-section"><h2>기본정보</h2><div class="detail-facts"><dl><dt>대표자</dt><dd>${esc(c.representativeName??"—")}</dd><dt>기업형태</dt><dd>${esc(c.companyType??"—")}</dd><dt>상태</dt><dd>${esc(c.companyStatus??"—")}</dd><dt>설립일</dt><dd>${esc(c.establishedDate??"—")}</dd></dl><dl><dt>업종</dt><dd>${esc(c.industryName??"—")} ${esc(c.ksicCode??"")}</dd><dt>주요제품</dt><dd>${esc(c.mainProducts??"—")}</dd><dt>주소</dt><dd>${esc(c.roadAddress??c.address??"—")}</dd><dt>홈페이지</dt><dd>${safeUrl(c.homepageUrl)?`<a href="${esc(safeUrl(c.homepageUrl))}" target="_blank" rel="noreferrer">${esc(safeUrl(c.homepageUrl))}</a>`:"—"}</dd></dl></div></article><article class="detail-section"><h2>매출현황</h2>${unitControls()}${rows(d.financialStatements,[["fiscalYear","연도"],["revenue","매출액"],["operatingIncome","영업이익"],["netIncome","당기순이익"],["totalAssets","총자산"]])}</article><article class="detail-section"><h2>사업장정보</h2>${rows(d.businessSites,[["siteName","사업장명"],["siteType","구분"],["businessNumber","사업자번호"],["address","주소"]])}</article><article class="detail-section"><h2>연혁</h2>${rows(d.histories,[["eventDate","일자"],["description","내용"]])}</article></section>`;};
