import "./styles.css";
import { companyRepository, isDemoMode } from "./data";
import { loadFavorites, saveFavorites } from "./favorites";
import type { Company, CompanyDetail, CompanySearchResult, Domain, IndustryOption, SortOption, View } from "./types";

const app=document.querySelector<HTMLDivElement>("#app")!;
const views:View[]=["search","dash","analysis"];
const labels:Record<View,string>={search:"Search",dash:"Dash",analysis:"Analysis"};
let domain:Domain="company", view:View="search", query="", industry="", sort:SortOption="name-asc", page=1;
let result:CompanySearchResult={rows:[],total:0,page:1,totalPages:1};
let industries:IndustryOption[]=[], selected:CompanyDetail|undefined, loading=false, error="", timer:number|undefined, sequence=0;
const favorites=loadFavorites();
const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const amount=(value?:number)=>value==null?"—":`${value.toLocaleString()}백만원`;

const shell=(content:string)=>`<header class="topbar"><div class="topbrand"><span>MR</span><div><b>MONA RADAR</b><small>DATA INTELLIGENCE</small></div></div><div class="domain-switch" role="group" aria-label="데이터 영역"><button data-domain="company" class="${domain==="company"?"active":""}">Company</button><button data-domain="facility" class="${domain==="facility"?"active":""}">Facility</button></div></header><div class="shell"><aside><div><p class="aside-label">WORKSPACE</p><nav>${views.map((item)=>`<button data-view="${item}" class="${item===view?"active":""}"><span>${labels[item]}</span><small>${item==="search"?"데이터 찾기":item==="dash"?"현황 보기":"패턴 분석"}</small></button>`).join("")}</nav></div><footer>MONA RADAR<br><span>WEB EDITION · 0.1</span></footer></aside><main>${content}</main></div>`;

const pagination=()=>result.totalPages<=1?"":`<nav class="pagination" aria-label="검색 결과 페이지"><button data-page="${result.page-1}" ${result.page<=1?"disabled":""}>이전</button>${Array.from({length:result.totalPages},(_,i)=>i+1).filter((p)=>Math.abs(p-result.page)<=2).map((p)=>`<button data-page="${p}" class="${p===result.page?"active":""}">${p}</button>`).join("")}<button data-page="${result.page+1}" ${result.page>=result.totalPages?"disabled":""}>다음</button></nav>`;
const resultCard=(row:Company)=>`<article class="company-card" data-company="${esc(row.companyId)}" tabindex="0"><div class="company-title"><div><b>${esc(row.companyName)}</b><small>${esc(row.businessNumber??row.sminfoKcd)}</small></div><div class="card-actions"><span>${esc(row.companyStatus??"상태 미표시")}</span><button class="favorite ${favorites.has(row.companyId)?"active":""}" data-favorite="${esc(row.companyId)}" aria-label="즐겨찾기 ${favorites.has(row.companyId)?"해제":"추가"}">${favorites.has(row.companyId)?"★":"☆"}</button></div></div><div class="company-grid"><dl><dt>대표자</dt><dd>${esc(row.representativeName??"—")}</dd><dt>기업형태</dt><dd>${esc(row.companyType??"—")}</dd><dt>설립일</dt><dd>${esc(row.establishedDate??"—")}</dd></dl><dl><dt>업종</dt><dd>${esc(row.industryName??"—")} ${row.ksicCode?`<small>${esc(row.ksicCode)}</small>`:""}</dd><dt>주요제품</dt><dd>${esc(row.mainProducts??"—")}</dd><dt>주소</dt><dd>${esc(row.roadAddress??row.address??"—")}</dd></dl><dl class="financial"><dt>최근 결산</dt><dd>${esc(row.fiscalYear??"—")}</dd><dt>매출액</dt><dd>${amount(row.revenueKrwMillion)}</dd><dt>영업이익</dt><dd>${amount(row.operatingIncomeKrwMillion)}</dd><dt>당기순이익</dt><dd>${amount(row.netIncomeKrwMillion)}</dd></dl></div></article>`;

const searchView=()=>`<section class="page"><header class="page-head"><div><p class="eyebrow">COMPANY INDEX</p><h1>기업 검색</h1><p>기업명부터 대표자, 제품, 주소와 업종까지 한 번에 찾아보세요.</p></div>${isDemoMode?'<span class="demo-badge">DEMO DATA</span>':""}</header><div class="search-panel"><label class="search-input"><span>⌕</span><input id="search" value="${esc(query)}" placeholder="기업명·대표자·사업자번호·제품·주소·업종 검색" autocomplete="off"></label><div class="filters"><label><span>업종</span><select id="industry"><option value="">전체 업종</option>${industries.map((x)=>`<option value="${esc(x.id)}" ${industry===x.id?"selected":""}>${esc(x.name)}</option>`).join("")}</select></label><label><span>정렬</span><select id="sort"><option value="name-asc" ${sort==="name-asc"?"selected":""}>기업명순</option><option value="revenue-desc" ${sort==="revenue-desc"?"selected":""}>매출액 높은순</option><option value="recent-desc" ${sort==="recent-desc"?"selected":""}>최근 수집순</option></select></label><span class="count"><b>${result.total.toLocaleString()}</b>개 기업</span></div></div>${error?`<div class="error">${esc(error)}</div>`:""}<div class="result-meta"><span>${query?`‘${esc(query)}’ 검색 결과`:"전체 기업"}</span><small>페이지당 10개</small></div><div class="results ${loading?"loading":""}">${loading?'<div class="empty">기업 데이터를 불러오는 중입니다.</div>':result.rows.length?result.rows.map(resultCard).join(""):'<div class="empty"><b>검색 결과가 없습니다.</b><span>검색어나 필터를 바꿔보세요.</span></div>'}</div>${pagination()}</section>`;
const rows=(data:Record<string,unknown>[],columns:[string,string][])=>data.length?`<div class="detail-table"><div class="detail-row head">${columns.map(([,label])=>`<b>${label}</b>`).join("")}</div>${data.map((row)=>`<div class="detail-row">${columns.map(([key])=>`<span>${esc(row[key]??"—")}</span>`).join("")}</div>`).join("")}</div>`:'<div class="detail-empty">등록된 정보가 없습니다.</div>';
const detailView=()=>{const d=selected!,c=d.company; return `<section class="page detail"><button class="back" data-back>← 기업 검색으로 돌아가기</button><header class="page-head"><div><p class="eyebrow">COMPANY DETAIL</p><h1>${esc(c.companyName)}</h1><p>${esc(c.businessNumber??c.sminfoKcd)} · 데이터 기준 ${esc(c.lastCollectedAt??"—")}</p></div><button class="detail-favorite ${favorites.has(c.companyId)?"active":""}" data-favorite="${esc(c.companyId)}">${favorites.has(c.companyId)?"★ 즐겨찾기됨":"☆ 즐겨찾기"}</button></header><article class="detail-section"><h2>기본정보</h2><div class="detail-facts"><dl><dt>대표자</dt><dd>${esc(c.representativeName??"—")}</dd><dt>기업형태</dt><dd>${esc(c.companyType??"—")}</dd><dt>상태</dt><dd>${esc(c.companyStatus??"—")}</dd><dt>설립일</dt><dd>${esc(c.establishedDate??"—")}</dd></dl><dl><dt>업종</dt><dd>${esc(c.industryName??"—")} ${esc(c.ksicCode??"")}</dd><dt>주요제품</dt><dd>${esc(c.mainProducts??"—")}</dd><dt>주소</dt><dd>${esc(c.roadAddress??c.address??"—")}</dd><dt>홈페이지</dt><dd>${c.homepageUrl?`<a href="${esc(c.homepageUrl)}" target="_blank" rel="noreferrer">${esc(c.homepageUrl)}</a>`:"—"}</dd></dl></div></article><article class="detail-section"><h2>매출현황</h2>${rows(d.financialStatements,[["fiscalYear","연도"],["revenue","매출액"],["operatingIncome","영업이익"],["netIncome","당기순이익"],["totalAssets","총자산"]])}</article><article class="detail-section"><h2>사업장정보</h2>${rows(d.businessSites,[["siteName","사업장명"],["siteType","구분"],["businessNumber","사업자번호"],["address","주소"]])}</article><article class="detail-section"><h2>연혁</h2>${rows(d.histories,[["eventDate","일자"],["description","내용"]])}</article></section>`;};
const placeholder=()=>`<section class="page placeholder"><p class="eyebrow">MONA RADAR / ${domain.toUpperCase()}</p><h1>${labels[view]}</h1><div class="orb"></div><h2>${domain==="facility"?"Facility 영역을 준비하고 있습니다":`${labels[view]}를 준비하고 있습니다`}</h2><p>${domain==="facility"?"시설 데이터 모델과 API가 연결되면 이 화면에서 조회하고 분석할 수 있습니다.":"데이터 연결 이후 실제 지표와 분석 화면이 제공됩니다."}</p></section>`;
function render(){const content=domain==="company"&&view==="search"?(selected?detailView():searchView()):placeholder();app.innerHTML=shell(content);bind();}
async function load(nextPage=1){const id=++sequence;loading=true;error="";render();try{const value=await companyRepository.search({query,industry,sort,page:nextPage,pageSize:10});if(id!==sequence)return;result=value;page=value.page;}catch(e){if(id!==sequence)return;error=e instanceof Error?e.message:String(e);}finally{if(id===sequence){loading=false;render();}}}
function toggleFavorite(id:string){favorites.has(id)?favorites.delete(id):favorites.add(id);saveFavorites(favorites);render();}
function bind(){document.querySelectorAll<HTMLButtonElement>("[data-domain]").forEach((button)=>button.onclick=()=>{domain=button.dataset.domain as Domain;selected=undefined;render();if(domain==="company"&&view==="search")void load(1);});document.querySelectorAll<HTMLButtonElement>("[data-view]").forEach((button)=>button.onclick=()=>{view=button.dataset.view as View;selected=undefined;render();if(domain==="company"&&view==="search")void load(1);});const input=document.querySelector<HTMLInputElement>("#search");if(input){input.oninput=()=>{query=input.value;clearTimeout(timer);timer=window.setTimeout(()=>void load(1),180);};}document.querySelector<HTMLSelectElement>("#industry")?.addEventListener("change",(e)=>{industry=(e.target as HTMLSelectElement).value;void load(1);});document.querySelector<HTMLSelectElement>("#sort")?.addEventListener("change",(e)=>{sort=(e.target as HTMLSelectElement).value as SortOption;void load(1);});document.querySelectorAll<HTMLButtonElement>("[data-page]").forEach((button)=>button.onclick=()=>void load(Number(button.dataset.page)));document.querySelectorAll<HTMLButtonElement>("[data-favorite]").forEach((button)=>button.onclick=(event)=>{event.stopPropagation();toggleFavorite(button.dataset.favorite!);});document.querySelectorAll<HTMLElement>("[data-company]").forEach((card)=>{const open=async()=>{try{selected=await companyRepository.getDetail(card.dataset.company!);render();}catch(e){error=String(e);render();}};card.onclick=(event)=>{if(!(event.target as HTMLElement).closest("a,button"))void open();};card.onkeydown=(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();void open();}};});document.querySelector<HTMLButtonElement>("[data-back]")?.addEventListener("click",()=>{selected=undefined;render();});}
async function start(){render();try{industries=await companyRepository.listIndustries();await load();}catch(e){error=e instanceof Error?e.message:String(e);render();}}
void start();
